version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "tolicodes/tolicodes.com"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  deploy:
    image: codefresh/plugin-kompose:v1.5.0
    environment:
      - KUBE_CONTEXT=gke-zoomevents-cluster-default-pool-c59c4b04-86ww
      - NAMESPACE=${{NAMESPACE}}
      - FILE=docker-compose.production.yml
