version: "3.4"
services:
  frontend:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    image: tolicodes/tolicodes.com
    labels:
      - kompose.service.type=nodeport
      - kompose.service.expose=wildcard.tolicodes.com
